/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BigNav: typeof import('./components/Site/BigNav.vue')['default']
    BlurredCircle: typeof import('./components/Creative/BlurredCircle.vue')['default']
    BubbleGrid: typeof import('./components/Creative/BubbleGrid.vue')['default']
    Contact: typeof import('./components/Module/Contact.vue')['default']
    Container: typeof import('./components/Modal/Container.vue')['default']
    Content: typeof import('./components/Modal/Content.vue')['default']
    DotGrid: typeof import('./components/Creative/DotGrid.vue')['default']
    DotGridLeft: typeof import('./components/Creative/DotGridLeft.vue')['default']
    DotGridRight: typeof import('./components/Creative/DotGridRight.vue')['default']
    Error: typeof import('./components/General/Error.vue')['default']
    Event: typeof import('./components/Card/Event.vue')['default']
    Events: typeof import('./components/Module/Events.vue')['default']
    FadeIn: typeof import('./components/Creative/FadeIn.vue')['default']
    Footer: typeof import('./components/Site/Footer.vue')['default']
    Gallery: typeof import('./components/Module/Gallery.vue')['default']
    GeneralContainer: typeof import('./components/GeneralContainer.vue')['default']
    Landing: typeof import('./components/Module/Landing.vue')['default']
    Lives: typeof import('./components/Svg/Lives.vue')['default']
    Logo: typeof import('./components/Svg/Logo.vue')['default']
    Mission: typeof import('./components/Module/Mission.vue')['default']
    Nav: typeof import('./components/Site/Nav.vue')['default']
    Partner: typeof import('./components/Card/Partner.vue')['default']
    Partners: typeof import('./components/Module/Partners.vue')['default']
    Profile: typeof import('./components/Card/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveLives: typeof import('./components/Svg/SaveLives.vue')['default']
    SectionTitle: typeof import('./components/General/SectionTitle.vue')['default']
    Space: typeof import('./components/General/Space.vue')['default']
    SVLCircle: typeof import('./components/Svg/SVLCircle.vue')['default']
    Team: typeof import('./components/Module/Team.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
  }
}
